tables:
  - name: "silver_flights"
    source: "bronze.flights"
    stage_view: "trans_flights"
    transformations:
      - to_date: {"flight_date": "yyyy-MM-dd"}
      - add_column: {"modifiedDate": "current_timestamp()"}
      - drop_columns: ["_rescued_data"]
    cdc:
      type: "scd1"
      keys: ["flight_id"]
      sequence_by: "modifiedDate"
