autoloader:
  format: "cloudFiles"
  file_format: "csv"
  options:
    header: "true"
    inferSchema: "true"
    schemaEvolutionMode: "addNewColumns"

  checkpoint_location: "/Volumes/workspace/flight_bronze/bronzevolume/{table}/checkpoint/"
  target_path: "/Volumes/workspace/flight_bronze/bronzevolume/{table}/data/"
  source_path: "/Volumes/workspace/flight_raw/raw_volume/rawdata/{table}/"

  tables:
    - bookings
    - flights
    - customers
    - airports
