# configs/silver_pipeline.yml
pipeline_name: flight_silver_pipeline

sources:
  bookings:
    path: /Volumes/workspace/flight_bronze/bronzevolume/bookings/data
    format: delta
    output: stage_bookings
    transformations:
      - cast:
          column: amount
          type: double
      - with_column:
          name: modifiedDate
          expr: current_timestamp()
      - cast:
          column: booking_date
          type: date
      - drop: [_rescued_data]
    expectations:
      rule1: "booking_id IS NOT NULL"
      rule2: "passenger_id IS NOT NULL"
    target: silver_bookings

  flights:
    path: /Volumes/workspace/flight_bronze/bronzevolume/flights/data/
    format: delta
    output: trans_flights
    transformations:
      - cast:
          column: flight_date
          type: date
      - drop: [_rescued_data]
      - with_column:
          name: modifiedDate
          expr: current_timestamp()
    target: silver_flights
    cdc:
      keys: [flight_id]
      sequence_by: modifiedDate
      scd_type: 1

  passengers:
    path: /Volumes/workspace/flight_bronze/bronzevolume/customers/data/
    format: delta
    output: trans_passengers
    transformations:
      - drop: [_rescued_data]
      - with_column:
          name: modifiedDate
          expr: current_timestamp()
    target: silver_passengers
    cdc:
      keys: [passenger_id]
      sequence_by: modifiedDate
      scd_type: 1

  airports:
    path: /Volumes/workspace/flight_bronze/bronzevolume/airports/data/
    format: delta
    output: trans_airports
    transformations:
      - drop: [_rescued_data]
      - with_column:
          name: modifiedDate
          expr: current_timestamp()
    target: silver_airports
    cdc:
      keys: [airport_id]
      sequence_by: modifiedDate
      scd_type: 1

business_view:
  name: silver_business
  join:
    - left: silver_bookings
      right: silver_flights
      keys: [flight_id]
    - left: silver_bookings
      right: silver_passengers
      keys: [passenger_id]
    - left: silver_bookings
      right: silver_airports
      keys: [airport_id]
  drop_columns: [modifiedDate]
